config/routes.rb
Store::Application.routes.draw do
  
  
  
  resources :calls

  get "tropo/callback"
  post "tropo/callback"
  get "tropo/index"

  get "tropo/recordings"

  resources :autoresponders
  
  post "api/parse_google_search"
  get "api/pending_emails"
  post "api/process_emails"
  post "api/process_scan"
  post "api/process_website"
  get "api/process_website"
  get "api/channel_scanned"
  get "api/email_status"
  get "api/export_brand"
  get "api/brands"
  get "api/scan_plan"
  post "api/scan"
  post "api/logs"
  get "api/scan"
  get "api/monitor"

  get 'trackers/load'
  resources :trackers
  resources :scores

  get "emails/delete_all"
  get "emails/send_email"
  resources :emails

  get "feed_entries/show"
  get "feed_entries/deploy"

  resources :tutorials

  post "bulk_mails/add_articles"
  post "bulk_mails/configure"
  get "bulk_mails/move_article"
  get "bulk_mails/stats"
  get "bulk_mails/configure"
  post "bulk_mails/import"
  get "bulk_mails/import"
  get "bulk_mails/duplicate"
  get "bulk_mails/check"
  get "bulk_mails/stop"
  get "bulk_mails/start"
  get "bulk_mails/preview"
  resources :bulk_mails

  resources :forum_posts

  resources :topics

  resources :colors

  resources :mentions

  resources :tickets
  resources :feed_entries

  
  
  get "posts/email_action"
  get "posts/post_to"
  get "posts/repost"
  get "posts/preview"
  get "posts/deploy_to_facebook"
  get "posts/add_to_delayed"
  get "posts/retweet"
  get "posts/follow_user"
  
  get "brands/templates"
  get "brands/search"
  get "brands/searches"
  get "brands/recommendations"
  get "brands/connections"
  get "brands/disconnect"
  get "brands/map"
  get "brands/reading"
  get "brands/exposure"
  get "brands/twitter_search"
  get "brands/twitter_mentions"
  get "brands/repost_rss_items"
  
  
  
  
  get "admin/find_people"
  get "admin/page_preview"
  get "admin/website_templates"
  get "admin/email_templates"
  get "admin/licenses"
  get "admin/licenses"
  get "admin/test"
  get "admin/bgc"

  get "admin/background_jobs"

  get "admin/timeline_json"
  get "admin/reader"
  get "admin/index"
  get "admin/users"
  get "admin/refresh_rss"
  get "admin/delete_all_jobs"
  get "admin/delete_job"
  get "admin/posts"
  get "admin/comments"
  get "admin/websites"

  
  get "slides/create"

  get "slides/edit"

  get "slides/destroy"

  get "slides/index"

  get "slides/update"

  get "slides/new"

  get "channels/create_short_link"
  get "channels/remove_feed"
  get "channels/add_feed"
  get "channels/register"
  post "channels/register"
  get "channels/ignore"
  get "channels/scan"
  get "channels/index"
  get "channels/show"
  post "channels/update"

  get "/users/reset_user"
  get "/users/delete_user"
  
  resources :slides
  resources :channels
  resources :posts

  resources :deployments

  resources :messages

  resources :groups

  get "analysis/index"
  get "analysis/callback"
  get "analysis/fans"
  get "analysis/social_networks"
  get "analysis/mentions"
  get "analysis/website"
  post "analysis/website"
  get "analysis/mailing_list"

  get "inquieries/reply"
  resources :inquieries

  resources :feeds

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions  

  
  
  post "public/form_post"
  get "public/campaign"
  get "public/newsletter"
  get "public/event"
  get "public/email_verification"
  get "public/unsubscribe_from_email"
  get "public/elections"
  get "public/index_heb"
  get "public/meetup"
  get "public/event"
  get "public/facebook_page_public"
  get "public/facebook_page_private"
  get "public/index"
  get "public/tour"
  get "public/blog"
  get "public/prices"
  get "public/beta"
  get "public/store"
  get "public/product"
  get "public/article"
  get "public/register"
  get "public/login"
  get "public/brands"
  get "public/brand"

  get "brands/timeline"
  get "brands/stream"
  get "brands/scan_brand"
  get "brands/social_dashboard"
  get "brands/social_login_callback"
  get "brands/social_login_failure"
  
  match "/auth/:provider/callback", to: "brands#social_login_callback"
  match "/auth/failure", to: "brands#social_login_failure"

  get "page_partials/row_settings"
  get "page_partials/images"
  get "/page_partials/replace_with"
  post "/page_partials/quick_update"
  resources :page_partials

  get "pages/copy_template"
  get "pages/preview_inner"
  get "pages/make_template"
  get "pages/save_colors"
  get "pages/create_page"
  get "pages/add_line"
  get "pages/set_css_template"
  get "pages/export"
  get "pages/add_line"
  get "pages/hero_row"
  get "pages/move_row_top"
  get "pages/move_row_bottom"
  get "pages/move_row_up"
  get "pages/move_row_down"
  get "pages/remove_row"
  get "pages/preview"
  get "pages/css"
  get "pages/layout"
  get "pages/js"
  resources :pages
  
  get "websites/move_page"
  get "websites/create_page"
  get "websites/reset_custom_colors"
  get "websites/apply_color_patch"
  get "websites/css"
  get "websites/stats"
  resources :websites

  get "research/index"
  get "research/rss"
  get "research/people"
  get "research/news"
  get "research/competitors"
  get "research/groups"
  get "research/twitter"

  get "research/groups"
  get "articles/new_article"
  get "articles/publish"
  get "articles/deploy_to_twitter"
  get "articles/deploy_to_facebook_page"
  get "articles/deploy_to_blog_via_email"

  resources :bookmarks

  get "/templates/duplicate"
  get "/templates/preview"
  resources :templates

  resources :email_listings
  get "competitors/scan"
  match '/competitors/:id/scan' => "competitors#scan"
  
  
  get "events/publish"
  get "events/deploy"
  
  post "fans/import"
  get "fans/import"
  get "fans/invite"
  get "fans/ignore" 
  get "fans/search" 
  get "fans/scan" 
  get "fans/follow" 
  get "fans/unfollow" 
  get "fans/competitor" 
  get "fans/charts" 
  
  
  get "products/charts" 
  get "events/charts" 
  
  
  match '/events/:id/publish' => "events#publish"
  match '/events/:id/deploy' => "events#deploy"
  resources :events
  resources :competitors
  resources :comments
  resources :fans
  resources :users
  resources :articles
  resources :brands
  resources :products
  
  get "channels/scan"
  
  match '/channels/:id/scan' => "channels#scan"
  match 'blog/:id' => "public#blog"
  match 'store/:id' => "public#store"
  match 'site/:id' => "public#brand"
  

  root :to => 'public#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/inquiery.rb
class Inquiery < ActiveRecord::Base
  belongs_to :brand
  belongs_to :article
  belongs_to :product
  
#   require "gmail_sender"
  def send_email(to, subject , body)
    begin
      Email.new(
        :brand_id => self.brand_id,
        :kind     => "autorespond",
        :subject  => subject,
        :text_body     => body,
        :to_email => to,
        :to_name  => self.name,
        :status   => "pending"
      ).save
      puts "### -- SENDINF EMAIL to  " + to
      g = GmailSender.new(self.brand.gmail_email, self.brand.gmail_pwd)
      g.send( :to => to,   :subject => subject,  :content => body)
    rescue Exception => e
      puts "Email was not sent. " + e.message
    end
  end
  
  
  def facebook?
    self.source and self.source.include? "facebook"
  end
  
  def auto_response
    puts "AUTO_RESPONSE"
    send_email(self.email, "SocialMachine Beta Registration", "Thank you for registering to the SocialMachine. We will Contact you with your account info soon")
  end
  
  def notify
    puts "NOTIFY"
    send_email(self.brand.gmail_email, "Notification from your SocialMachine website!", "You got new messaeg.  from #{self.name} #{self.email}<br/>#{self.message}")
  end
  
end

app/controllers/inquieries_controller.rb
class InquieriesController < ApplicationController
  def authorize
    true
  end
  
  def reply
    #    raise params.inspect
    @inquiery = current_user.brand.inquieries.find(params[:id])
    @template = BulkMail.find(params[:mail])
    @email = Email.new
    @email.to_email = @inquiery.email
    @email.to_name = @inquiery.name
    @email.text_body = (@template.body.gsub("#user", @inquiery.name))
    @email.html_body = (@template.body.gsub("#user", @inquiery.name)).to_s
  end
  
  def index
    @inquieries = current_user.brand.inquieries.order("created_at DESC")
  end

  def show
    @inquiery = current_user.brand.inquieries.find(params[:id])
#    @google_results = google_search(@inquiery.name)
    @emails = BulkMail.where(:kind => "autoresponder" , :brand_id => current_user.brand.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inquiery }
    end
  end

  def new
    @inquiery = Inquiery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inquiery }
    end
  end

  def edit
    @inquiery = Inquiery.find(params[:id])
  end

  def create
    @inquiery = Inquiery.new(params[:inquiery])
    
    if @inquiery.save
      @inquiery.auto_response
      @inquiery.notify
      #      if @inquiery.facebook?
      #        redirect_to "/public/facebook_page_public", notice: 'Inquiery was successfully created.'
      #      else
      #      raise request.original_url.inspect
      redirect_to @inquiery.request_url, notice: 'Inquiery was successfully created.'
      #      end
    end
  end

  def update
    @inquiery = Inquiery.find(params[:id])

    respond_to do |format|
      if @inquiery.update_attributes(params[:inquiery])
        format.html { redirect_to @inquiery, notice: 'Inquiery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inquiery.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inquiery = Inquiery.find(params[:id])
    @inquiery.destroy

    respond_to do |format|
      format.html { redirect_to inquieries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inquieries_helper.rb
module InquieriesHelper
end

app/views/inquieries/_form.html.erb
<%= form_for @inquiery, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Inquiery</legend>

    <div class="control-group">
      <%= f.label :brand_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :brand_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :captcha_token, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :captcha_token, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :message, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => 'text_area' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', inquieries_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/inquieries/_google_image_search_js.erb
<script src="http://www.google.com/jsapi?key=ABQIAAAAr19Eul_kZsYCBnyMjSJbPhSS8zuUzs-phHbAd9SKTtjFtv728xQ8NcR0mWFbQ0Ita4R2Wzc7rTuWUQ" type="text/javascript"></script>
  

<script type="text/javascript">
    google.load("search", "1", {"nocss" : true});
    
    // function will bind event to all images
    function bind_event(){
      $("a.gs-image").bind("click", function(e){
        $("#redactor_file_link").text($(".gs-image",this).attr("src"));
        $( "#article_remote_image_url" ).attr("value", $(".gs-image",this).attr("src")); // copy the picture on the page too.
        $( "#article_image_preview" ).attr("src", $(".gs-image",this).attr("src")); // copy the picture on the page too.
        return false;
      });
        
      $("div.gsc-cursor").prepend("<div class='clear' style='margin-top:10px;clear:both;'></div>");
        
      $(".gsc-trailing-more-results").css("display","none");
        
    }

    // the se class encapsulates a left and right search control
    // both controls are driven by a shared search form
    function OnLoad() {
        
      // create a tabbed mode search control
      var tabbed = new google.search.SearchControl();        
        
      //restrict results: search only moderated
      //tabbed.setRestriction(google.search.RESTRICT_SAFESEARCH, google.search.SAFESEARCH_STRICT);
        
      // Set the Search Control to get the most number of results
      tabbed.setResultSetSize(google.search.Search.LARGE_RESULTSET);
        
      // create image searchers.
      tabbed.addSearcher(new google.search.ImageSearch());
        
      // proprofscc: On search completeion
      tabbed.setSearchCompleteCallback(this, bind_event);
        
      // draw in tabbed layout mode
      var drawOptions = new google.search.DrawOptions();
      drawOptions.setDrawMode(google.search.SearchControl.DRAW_MODE_TABBED);
        
      // Draw the tabbed view in the content div
      tabbed.draw(document.getElementById("imgSearchControl"), drawOptions);
        
      // Search!
      tabbed.execute("");
    }
    
    google.setOnLoadCallback(OnLoad);
    
  </script>

  <style type="text/css">

    body{color:#888;}

    .search-control {
      width : auto;
      font-size:0.9em;
      color:#777;
    }

    /*---- Override existing Google Image Search Layout----------- **/
    .gs-text-box, .gsc-tabhActive, .gs-watermark, .gsc-branding, .gsc-twiddle, .gsc-stats, .gsc-results-selector, .gsc-all-results-active{display:none;}

    /*-----Search Box---*/
    .gsc-input input{ padding:6px 5px 6px 5px; margin-top: 5px; color:#aaa; border:2px solid #ccc; -moz-border-radius:4px; -webkit-border-radius:4px;}
    input.gsc-search-button, .ui-widget button{ margin: 5px 0 0 5px;}

    /*-----Image ---*/
    img.gs-image{float:left; margin:10px 10px 20px 0px; width:32px; height:32px; border:5px solid #fff; padding:1px; -moz-border-radius:4px; -webkit-border-radius:4px;}
    img.gs-image:hover{border:5px solid #aaa;width:150px; height:150px;}
    img.selectImage{float:left; margin:10px 10px 20px 0px; width:190px; height:180px; border:5px solid #aaa; padding:1px; -moz-border-radius:4px; -webkit-border-radius:4px;}

    /*--Paging---**/
    .gsc-cursor-page{float:left; text-shadow: 1px 1px 1px #fff; cursor: pointer; margin: 0px 8px 10px 0px; padding: 3px 7px 3px 7px; background: #ddd; color:#000; border:1px solid #999; -moz-border-radius:2px; -webkit-border-radius:2px;}
    .gsc-cursor-page:hover{ background: #fff; color:#333;}
    .gsc-cursor-current-page{background: #fff; color:#333;}

    /****Demo Page Formatting****/
    .clear{clear: both;}

    /**** Result Image ****/
    #imageContainer img{padding:1px; border:1px solid #ddd; width: auto; height: auto;}

  </style>

app/views/inquieries/edit.html.erb
<%= render :partial => 'form' %>

app/views/inquieries/index.html.erb
<div class="row-fluid thumbnail">
  <div class="modal-header">
    <h2><%= image_tag "/assets/flat/edit-5-64.png" , :size => "48x48" %> Inquiries</h2>
  </div>
  <div class="modal-header">
    <table class="table xdatatable">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>email</th>
          <th>message</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @inquieries.reverse.each do |inquiery| %>
          <tr>
            <td><%= inquiery.id %></td>
            <td><%= link_to inquiery.name, inquiery_path(inquiery) %></td>
            <td><%= link_to inquiery.message, inquiery_path(inquiery) || "" %></td>
            <td><%= link_to inquiery.email, inquiery_path(inquiery) || "" %></td>
            <td>
              <%= link_to 'Destroy', inquiery_path(inquiery), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/inquieries/index.mobile.erb
<% @brand = current_user.brand %>


<subview ui-associations="withNavBar ">
<scrollpanel>
  <tableview>
    <tableheader>
     Incomming messages
      </tableheader>
    
    <% for post in @inquieries do  %>
        <tablecell ui-usage="image">
          <celltitle><%= link_to post.name , post%></celltitle>
          <celldetail><%= link_to strip_html(post.message) , post%> <br/> <%= post.email  %> </celldetail>
        </tablecell>
      <% end %>

    </tableview>

  </scrollpanel>
</subview>

app/views/inquieries/new.html.erb
<%= render :partial => 'form' %>

app/views/inquieries/reply.erb
<%= form_for @email, :html => { :class => 'form-horizontal' } do |f| %>

<%= f.hidden_field :brand_id, :class => 'number_field' %>

  <div class="control-group">
    <%= f.label :to_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :to_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text_body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text_body, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :html_body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :html_body, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                emails_path, :class => 'btn' %>
  </div>
<% end %>

app/views/inquieries/show.html.erb
<%= render :partial => 'shared/upper_row' %>
<div class="row-fluid">

  <div class="span12">
    <div class="thumbnail">
      <div class="modal-header">
         <h2> <%= image_tag "/assets/flat/edit-5-64.png"  %> User Inquiry</h2>
      </div>
      <div class="tabbable ">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#1" data-toggle="tab">Inquiery</a></li>
        </ul>
        <div class="tab-content">

          <div class="tab-pane active" id="1">

            <div class="modal-header">
              <div class="pull-right">
                <div class="btn-group">
                  <button type="submit" class="btn">Reply to email</button>
                  <a class="btn  dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href=""><i class="icon-pencil"></i> write a messags</a></li>
                    <li class="divider"></li>
                    <% for item in BulkMail.where(:kind => "autoresponder") do  %>
                        <li><a  data-toggle="modal"  class="cmd-new-email" href="#mailModal"  data-body="<%=item.body%>" data-email="<%= @inquiery.email %>"  ><i class="icon-envelope"></i> <%= item.name %></a></li>
                      <% end %>
                    </ul>
                  </div>
                  <%= link_to 'Delete', inquiery_path(@inquiery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
                </div>

                <h3>Message from <%= @inquiery.name %></h3>
              </div>

              <div class="modal-header">
                <p>
                  <b>Name</b><br>
                  <%= @inquiery.name %>
                </p>

                <p>
                  <b>Recieved:</b><br>
                  <%= time_ago_in_words  @inquiery.created_at %>
                </p>
                <p>
                  <b>Email</b><br>
                  <%= @inquiery.email %>
                </p>

                <p>
                  <b>Message</b><br>
                  <%= @inquiery.message %>
                </p>

                <p>
                  <b>Source</b><br>
                  <%= @inquiery.request_url %>
                </p>

              </div>
            </div>





              <div class="tab-pane" id="3">
                <h5>picture of <%= @inquiery.name%></h5>
                <div id="imgSearchControl" class="search-control">Loading...</div>
                <!--Remove all floating-->

                <div class="clear"></div>

                <!--Image will be shown here-->
                <div id='imageContainer'></div>
              </div>

            </div>
          </div>
        </div>

      </div>

    </div>



    <%#= render :partial => 'shared/reply_dialog' %>

    <%#= render :partial => 'google_image_search_js' %>

app/views/inquieries/show.mobile.erb
<% @brand  = current_user.brand %>

<subview ui-associations="withNavBar ">
  <scrollpanel>


    <tableview ui-kind="grouped icon"  style="display:none;" id="actions_bar">
      <tableheader>
        Recommended Actions
      </tableheader>
      <tablecell >
        <celltitle><%= link_to "Reply to #{@inquiery.name}"%></celltitle>
      </tablecell>
      <tablecell >
        <celltitle><%= link_to "Google  #{@inquiery.name}"%></celltitle>
      </tablecell>
      <tablecell >
        <celltitle><%= link_to "Add  #{@inquiery.name} to my contacts"%></celltitle>
      </tablecell>
      <tablecell >
        <celltitle>
          <%= link_to 'Destroy', inquiery_path(@inquiery), :method => :delete, :confirm => 'Are you sure?' %>
        </celltitle>
      </tablecell>
    </tableview>

    <tableview >
      <tableheader>
        From :<%= @inquiery.name %>
      </tableheader>
      <tablecell >
        <div style="padding:1em;">

          <%= time_ago_in_words @inquiery.created_at %> 

          <%= simple_format(@inquiery.message) %>
        </div>
      </tablecell>

    </tableview>


  </scrollpanel>
</subview>


<% content_for :action do  %>
  <a href ="" id="action_btn">
    <uibutton ui-implements="icon" ui-bar-align="left">
      <icon style="-webkit-mask-image: url(/assets/mobile/icons/icon_comment_add.png)"></icon>
    </uibutton>
  </a>
<% end %>

<style>

  tableview > tablecell img{
    display: none;
    width:100px;
    height:100px;
    float:left;
    padding:1em;

  }

  tableview > celltitle{
    font-family: sans-serif;
    font-size: 12px;
  }
  tableview > tablecell{
    font-family: sans-serif;
    font-size: 12px;
  }
</style>