config/routes.rb
Store::Application.routes.draw do
  
  
  
  resources :calls

  get "tropo/callback"
  post "tropo/callback"
  get "tropo/index"

  get "tropo/recordings"

  resources :autoresponders
  
  post "api/parse_google_search"
  get "api/pending_emails"
  post "api/process_emails"
  post "api/process_scan"
  post "api/process_website"
  get "api/process_website"
  get "api/channel_scanned"
  get "api/email_status"
  get "api/export_brand"
  get "api/brands"
  get "api/scan_plan"
  post "api/scan"
  post "api/logs"
  get "api/scan"
  get "api/monitor"

  get 'trackers/load'
  resources :trackers
  resources :scores

  get "emails/delete_all"
  get "emails/send_email"
  resources :emails

  get "feed_entries/show"
  get "feed_entries/deploy"

  resources :tutorials

  post "bulk_mails/add_articles"
  post "bulk_mails/configure"
  get "bulk_mails/move_article"
  get "bulk_mails/stats"
  get "bulk_mails/configure"
  post "bulk_mails/import"
  get "bulk_mails/import"
  get "bulk_mails/duplicate"
  get "bulk_mails/check"
  get "bulk_mails/stop"
  get "bulk_mails/start"
  get "bulk_mails/preview"
  resources :bulk_mails

  resources :forum_posts

  resources :topics

  resources :colors

  resources :mentions

  resources :tickets
  resources :feed_entries

  
  
  get "posts/email_action"
  get "posts/post_to"
  get "posts/repost"
  get "posts/preview"
  get "posts/deploy_to_facebook"
  get "posts/add_to_delayed"
  get "posts/retweet"
  get "posts/follow_user"
  
  get "brands/templates"
  get "brands/search"
  get "brands/searches"
  get "brands/recommendations"
  get "brands/connections"
  get "brands/disconnect"
  get "brands/map"
  get "brands/reading"
  get "brands/exposure"
  get "brands/twitter_search"
  get "brands/twitter_mentions"
  get "brands/repost_rss_items"
  
  
  
  
  get "admin/find_people"
  get "admin/page_preview"
  get "admin/website_templates"
  get "admin/email_templates"
  get "admin/licenses"
  get "admin/licenses"
  get "admin/test"
  get "admin/bgc"

  get "admin/background_jobs"

  get "admin/timeline_json"
  get "admin/reader"
  get "admin/index"
  get "admin/users"
  get "admin/refresh_rss"
  get "admin/delete_all_jobs"
  get "admin/delete_job"
  get "admin/posts"
  get "admin/comments"
  get "admin/websites"

  
  get "slides/create"

  get "slides/edit"

  get "slides/destroy"

  get "slides/index"

  get "slides/update"

  get "slides/new"

  get "channels/create_short_link"
  get "channels/remove_feed"
  get "channels/add_feed"
  get "channels/register"
  post "channels/register"
  get "channels/ignore"
  get "channels/scan"
  get "channels/index"
  get "channels/show"
  post "channels/update"

  get "/users/reset_user"
  get "/users/delete_user"
  
  resources :slides
  resources :channels
  resources :posts

  resources :deployments

  resources :messages

  resources :groups

  get "analysis/index"
  get "analysis/callback"
  get "analysis/fans"
  get "analysis/social_networks"
  get "analysis/mentions"
  get "analysis/website"
  post "analysis/website"
  get "analysis/mailing_list"

  get "inquieries/reply"
  resources :inquieries

  resources :feeds

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions  

  
  
  post "public/form_post"
  get "public/campaign"
  get "public/newsletter"
  get "public/event"
  get "public/email_verification"
  get "public/unsubscribe_from_email"
  get "public/elections"
  get "public/index_heb"
  get "public/meetup"
  get "public/event"
  get "public/facebook_page_public"
  get "public/facebook_page_private"
  get "public/index"
  get "public/tour"
  get "public/blog"
  get "public/prices"
  get "public/beta"
  get "public/store"
  get "public/product"
  get "public/article"
  get "public/register"
  get "public/login"
  get "public/brands"
  get "public/brand"

  get "brands/timeline"
  get "brands/stream"
  get "brands/scan_brand"
  get "brands/social_dashboard"
  get "brands/social_login_callback"
  get "brands/social_login_failure"
  
  match "/auth/:provider/callback", to: "brands#social_login_callback"
  match "/auth/failure", to: "brands#social_login_failure"

  get "page_partials/row_settings"
  get "page_partials/images"
  get "/page_partials/replace_with"
  post "/page_partials/quick_update"
  resources :page_partials

  get "pages/copy_template"
  get "pages/preview_inner"
  get "pages/make_template"
  get "pages/save_colors"
  get "pages/create_page"
  get "pages/add_line"
  get "pages/set_css_template"
  get "pages/export"
  get "pages/add_line"
  get "pages/hero_row"
  get "pages/move_row_top"
  get "pages/move_row_bottom"
  get "pages/move_row_up"
  get "pages/move_row_down"
  get "pages/remove_row"
  get "pages/preview"
  get "pages/css"
  get "pages/layout"
  get "pages/js"
  resources :pages
  
  get "websites/move_page"
  get "websites/create_page"
  get "websites/reset_custom_colors"
  get "websites/apply_color_patch"
  get "websites/css"
  get "websites/stats"
  resources :websites

  get "research/index"
  get "research/rss"
  get "research/people"
  get "research/news"
  get "research/competitors"
  get "research/groups"
  get "research/twitter"

  get "research/groups"
  get "articles/new_article"
  get "articles/publish"
  get "articles/deploy_to_twitter"
  get "articles/deploy_to_facebook_page"
  get "articles/deploy_to_blog_via_email"

  resources :bookmarks

  get "/templates/duplicate"
  get "/templates/preview"
  resources :templates

  resources :email_listings
  get "competitors/scan"
  match '/competitors/:id/scan' => "competitors#scan"
  
  
  get "events/publish"
  get "events/deploy"
  
  post "fans/import"
  get "fans/import"
  get "fans/invite"
  get "fans/ignore" 
  get "fans/search" 
  get "fans/scan" 
  get "fans/follow" 
  get "fans/unfollow" 
  get "fans/competitor" 
  get "fans/charts" 
  
  
  get "products/charts" 
  get "events/charts" 
  
  
  match '/events/:id/publish' => "events#publish"
  match '/events/:id/deploy' => "events#deploy"
  resources :events
  resources :competitors
  resources :comments
  resources :fans
  resources :users
  resources :articles
  resources :brands
  resources :products
  
  get "channels/scan"
  
  match '/channels/:id/scan' => "channels#scan"
  match 'blog/:id' => "public#blog"
  match 'store/:id' => "public#store"
  match 'site/:id' => "public#brand"
  

  root :to => 'public#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :fan
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @brand = current_user.brand 
   @posts = @brand.posts.where(:kind => "group")
   @groups = @brand.fans.where(:kind => "group")
   @recommended = @brand.fans.where(:kind => "recommened-group")
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Group</legend>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :owner, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :owner, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :channel, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :channel, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :owner_image_url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :owner_image_url, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :image_url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :image_url, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :members_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :members_count, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :posts_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :posts_count, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :url, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :last_update, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_update, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', groups_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/groups/edit.html.erb
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<div class="row-fluid">
  <div class="thumbnail">
    <div class="modal-header">
      <div class="pull-right item_command">
        <%= link_to raw("<i class='icon-bar-chart'></i> Group Statistics"), "" %>
      </div>
      <h2><%= image_tag "/assets/flat/user-14-64.png",:size => "48x48"%> Group Posts </h2>
    </div>

    <div class="modal-header">
      <div class="tabbable ">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#posts" data-toggle="tab">New Posts </a></li>
          <li><a href="#groups" data-toggle="tab">My Groups</a></li>
          <li class=""><a href="#recommended" data-toggle="tab">Recommended Groups</a></li>
        </ul>


        <div class="tab-content ">

          <div class="tab-pane active" id="posts">
            <table class=" table table-striped datatable" id="we">
              <thead>
                <tr>
                  <th width="100px">Title</th>
                  <th>Posts</th>
                </tr>
              </thead>
              <tbody>
                <% @posts.each do |post| %>
                  <tr>
                    <td><%=image_tag post.img , :size => "100x100"%> </td>
                    <td>

                      <b> <%= post.title %> |   <%= post.from_name %> </b><br/>
                      <%= post.plain_text %>
                      <div class="item_command">
                        <a href=""><i class="icon-share"></i> Share</a>
                        <a href="<%= post.target_link %>" target="_blank"><i class="icon-reply"></i> Reply</a>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>


          <div class="tab-pane " id="groups">
             <table class=" table table-striped datatable" id="we">
              <thead>
                <tr>
                  <th width="100px">Title</th>
                  <th>Posts</th>
                </tr>
              </thead>
              <tbody>
                <% @groups.each do |post| %>
                  <tr>
                    <td><%=image_tag post.image_url , :size => "100x100"%> </td>
                    <td>

                      <b> <%= post.name %>  </b><br/>
                      <%= post.bio %>
                      <div class="item_command">
                        <a href=""><i class="icon-remove"></i> Leave</a>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="tab-pane " id="recommended">
             <table class=" table table-striped datatable" id="we">
              <thead>
                <tr>
                  <th width="100px">Title</th>
                  <th>Posts</th>
                </tr>
              </thead>
              <tbody>
                <% @recommended.each do |post| %>
                  <tr>
                    <td><%=image_tag post.image_url , :size => "100x100"%> </td>
                    <td>

                      <b> <%= post.name %>  </b><br/>
                      <%= post.bio %>
                       <div class="item_command">
                        <a href=""><i class="icon-plus"></i> Join Group</a>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>

app/views/groups/new.html.erb
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<h1>Group</h1>

<p>
  <b>Title</b><br>
  <%= @group.title %>
</p>

<p>
  <b>Description</b><br>
  <%= @group.description %>
</p>

<p>
  <b>Owner</b><br>
  <%= @group.owner %>
</p>

<p>
  <b>Channel</b><br>
  <%= @group.channel %>
</p>

<p>
  <b>Owner image url</b><br>
  <%= @group.owner_image_url %>
</p>

<p>
  <b>Image url</b><br>
  <%= @group.image_url %>
</p>

<p>
  <b>Members count</b><br>
  <%= @group.members_count %>
</p>

<p>
  <b>Posts count</b><br>
  <%= @group.posts_count %>
</p>

<p>
  <b>Url</b><br>
  <%= @group.url %>
</p>

<p>
  <b>Last update</b><br>
  <%= @group.last_update %>
</p>

<div class="form-actions">
  <%= link_to 'Back', groups_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_group_path(@group), :class => 'btn' %>
  <%= link_to 'Delete', group_path(@group), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>