config/routes.rb
Store::Application.routes.draw do
  
  
  
  resources :calls

  get "tropo/callback"
  post "tropo/callback"
  get "tropo/index"

  get "tropo/recordings"

  resources :autoresponders
  
  post "api/parse_google_search"
  get "api/pending_emails"
  post "api/process_emails"
  post "api/process_scan"
  post "api/process_website"
  get "api/process_website"
  get "api/channel_scanned"
  get "api/email_status"
  get "api/export_brand"
  get "api/brands"
  get "api/scan_plan"
  post "api/scan"
  post "api/logs"
  get "api/scan"
  get "api/monitor"

  get 'trackers/load'
  resources :trackers
  resources :scores

  get "emails/delete_all"
  get "emails/send_email"
  resources :emails

  get "feed_entries/show"
  get "feed_entries/deploy"

  resources :tutorials

  post "bulk_mails/add_articles"
  post "bulk_mails/configure"
  get "bulk_mails/move_article"
  get "bulk_mails/stats"
  get "bulk_mails/configure"
  post "bulk_mails/import"
  get "bulk_mails/import"
  get "bulk_mails/duplicate"
  get "bulk_mails/check"
  get "bulk_mails/stop"
  get "bulk_mails/start"
  get "bulk_mails/preview"
  resources :bulk_mails

  resources :forum_posts

  resources :topics

  resources :colors

  resources :mentions

  resources :tickets
  resources :feed_entries

  
  
  get "posts/email_action"
  get "posts/post_to"
  get "posts/repost"
  get "posts/preview"
  get "posts/deploy_to_facebook"
  get "posts/add_to_delayed"
  get "posts/retweet"
  get "posts/follow_user"
  
  get "brands/templates"
  get "brands/search"
  get "brands/searches"
  get "brands/recommendations"
  get "brands/connections"
  get "brands/disconnect"
  get "brands/map"
  get "brands/reading"
  get "brands/exposure"
  get "brands/twitter_search"
  get "brands/twitter_mentions"
  get "brands/repost_rss_items"
  
  
  
  
  get "admin/find_people"
  get "admin/page_preview"
  get "admin/website_templates"
  get "admin/email_templates"
  get "admin/licenses"
  get "admin/licenses"
  get "admin/test"
  get "admin/bgc"

  get "admin/background_jobs"

  get "admin/timeline_json"
  get "admin/reader"
  get "admin/index"
  get "admin/users"
  get "admin/refresh_rss"
  get "admin/delete_all_jobs"
  get "admin/delete_job"
  get "admin/posts"
  get "admin/comments"
  get "admin/websites"

  
  get "slides/create"

  get "slides/edit"

  get "slides/destroy"

  get "slides/index"

  get "slides/update"

  get "slides/new"

  get "channels/create_short_link"
  get "channels/remove_feed"
  get "channels/add_feed"
  get "channels/register"
  post "channels/register"
  get "channels/ignore"
  get "channels/scan"
  get "channels/index"
  get "channels/show"
  post "channels/update"

  get "/users/reset_user"
  get "/users/delete_user"
  
  resources :slides
  resources :channels
  resources :posts

  resources :deployments

  resources :messages

  resources :groups

  get "analysis/index"
  get "analysis/callback"
  get "analysis/fans"
  get "analysis/social_networks"
  get "analysis/mentions"
  get "analysis/website"
  post "analysis/website"
  get "analysis/mailing_list"

  get "inquieries/reply"
  resources :inquieries

  resources :feeds

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions  

  
  
  post "public/form_post"
  get "public/campaign"
  get "public/newsletter"
  get "public/event"
  get "public/email_verification"
  get "public/unsubscribe_from_email"
  get "public/elections"
  get "public/index_heb"
  get "public/meetup"
  get "public/event"
  get "public/facebook_page_public"
  get "public/facebook_page_private"
  get "public/index"
  get "public/tour"
  get "public/blog"
  get "public/prices"
  get "public/beta"
  get "public/store"
  get "public/product"
  get "public/article"
  get "public/register"
  get "public/login"
  get "public/brands"
  get "public/brand"

  get "brands/timeline"
  get "brands/stream"
  get "brands/scan_brand"
  get "brands/social_dashboard"
  get "brands/social_login_callback"
  get "brands/social_login_failure"
  
  match "/auth/:provider/callback", to: "brands#social_login_callback"
  match "/auth/failure", to: "brands#social_login_failure"

  get "page_partials/row_settings"
  get "page_partials/images"
  get "/page_partials/replace_with"
  post "/page_partials/quick_update"
  resources :page_partials

  get "pages/copy_template"
  get "pages/preview_inner"
  get "pages/make_template"
  get "pages/save_colors"
  get "pages/create_page"
  get "pages/add_line"
  get "pages/set_css_template"
  get "pages/export"
  get "pages/add_line"
  get "pages/hero_row"
  get "pages/move_row_top"
  get "pages/move_row_bottom"
  get "pages/move_row_up"
  get "pages/move_row_down"
  get "pages/remove_row"
  get "pages/preview"
  get "pages/css"
  get "pages/layout"
  get "pages/js"
  resources :pages
  
  get "websites/move_page"
  get "websites/create_page"
  get "websites/reset_custom_colors"
  get "websites/apply_color_patch"
  get "websites/css"
  get "websites/stats"
  resources :websites

  get "research/index"
  get "research/rss"
  get "research/people"
  get "research/news"
  get "research/competitors"
  get "research/groups"
  get "research/twitter"

  get "research/groups"
  get "articles/new_article"
  get "articles/publish"
  get "articles/deploy_to_twitter"
  get "articles/deploy_to_facebook_page"
  get "articles/deploy_to_blog_via_email"

  resources :bookmarks

  get "/templates/duplicate"
  get "/templates/preview"
  resources :templates

  resources :email_listings
  get "competitors/scan"
  match '/competitors/:id/scan' => "competitors#scan"
  
  
  get "events/publish"
  get "events/deploy"
  
  post "fans/import"
  get "fans/import"
  get "fans/invite"
  get "fans/ignore" 
  get "fans/search" 
  get "fans/scan" 
  get "fans/follow" 
  get "fans/unfollow" 
  get "fans/competitor" 
  get "fans/charts" 
  
  
  get "products/charts" 
  get "events/charts" 
  
  
  match '/events/:id/publish' => "events#publish"
  match '/events/:id/deploy' => "events#deploy"
  resources :events
  resources :competitors
  resources :comments
  resources :fans
  resources :users
  resources :articles
  resources :brands
  resources :products
  
  get "channels/scan"
  
  match '/channels/:id/scan' => "channels#scan"
  match 'blog/:id' => "public#blog"
  match 'store/:id' => "public#store"
  match 'site/:id' => "public#brand"
  

  root :to => 'public#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/email_listing.rb
class EmailListing < ActiveRecord::Base
    belongs_to :template
    belongs_to :brand
end

app/controllers/email_listings_controller.rb
class EmailListingsController < ApplicationController
  # GET /email_listings
  # GET /email_listings.json
  def index
    @email_listings = EmailListing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @email_listings }
    end
  end

  # GET /email_listings/1
  # GET /email_listings/1.json
  def show
    @email_listing = EmailListing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @email_listing }
    end
  end

  # GET /email_listings/new
  # GET /email_listings/new.json
  def new
    @email_listing = EmailListing.new
    @templates = Template.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_listing }
    end
  end

  # GET /email_listings/1/edit
  def edit
    @email_listing = EmailListing.find(params[:id])
    @templates = Template.all
  end

  # POST /email_listings
  # POST /email_listings.json
  def create
    @email_listing = EmailListing.new(params[:email_listing])

    respond_to do |format|
      if @email_listing.save
        format.html { redirect_to @email_listing, notice: 'Email listing was successfully created.' }
        format.json { render json: @email_listing, status: :created, location: @email_listing }
      else
        format.html { render action: "new" }
        format.json { render json: @email_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_listings/1
  # PUT /email_listings/1.json
  def update
    @email_listing = EmailListing.find(params[:id])

    respond_to do |format|
      if @email_listing.update_attributes(params[:email_listing])
        format.html { redirect_to @email_listing, notice: 'Email listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_listings/1
  # DELETE /email_listings/1.json
  def destroy
    @email_listing = EmailListing.find(params[:id])
    @email_listing.destroy

    respond_to do |format|
      format.html { redirect_to email_listings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/email_listings_helper.rb
module EmailListingsHelper
end

app/views/email_listings/_auto_responders.erb
<table class="table">
  <thead>
    <tr>
      <th>Sent To</th>
      <th>Template</th>
      <th>Sent At</th>
      <th>Recepients</th>
      <th>Opened</th>
      <th>Engadged</th>
      <th>Unsubscribed</th>
    </tr>
  </thead>
  <tbody>
    <% 3.times do  %>
    <tr>
      <td> <%= Fan.first.name %> </td>
      <td> <%= lorem(4) %> </td>
      <td width="100px"> <%= Time.now.strftime("%m/%d/%y") %></td>
      <td width="80px">  <span class="badge badge-info"> <%= "No"  %> </span> </td>
      <td width="80px">  <span class="badge badge-success"> <%= "No" %> </span> </td>
      <td width="80px">  <span class="badge badge-success"> <%= "No" %> </span> </td>
      <td width="80px">  <span class="badge badge-important"> <%= "No" %> </span> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/email_listings/_form.html.erb
<%= form_for @email_listing, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Email Listing</legend>

    <div class="control-group">
      <%= f.label :brand_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :brand_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :draft, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :draft, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :template_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :template_id, @templates , "id" ,"name" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :header, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :header, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :body, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :image, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :image, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :movie, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :movie, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :footer, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :footer, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :daily, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :daily, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :weekly, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :weekly, :class => 'check_box' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :monthly, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :monthly, :class => 'check_box' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', email_listings_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/email_listings/_list.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Template</th>
      <th width="40px">Sent</th>
      <th width="40px">Opened</th>
      <th width="40px">Bounced</th>
      <th width="60px">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @email_listings.each do |email_listing| %>
      <tr>
        <td><%= email_listing.name %></td>
        <td><%= email_listing.template.name %></td>
        <td><span class="btn-info btn"> <%= rand(300)%> </span> </td>
        <td><span class="btn-success btn"> <%= rand(40)%> </span> </td>
        <td><span class="btn-danger btn"> <%= rand(20)%> </span> </td>
        <td>
          <%= link_to 'Edit', edit_email_listing_path(email_listing), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/email_listings/_listings.erb
<div class="row">

  <div class="span4">
    <div class="pull-right">
      <%= link_to "New Mail" ,"", :class => "btn" %>
    </div>
    <h3>All Fans</h3><hr/>
    <% for fan in Fan.all[0..30]  do %>
      <%= image_tag fan.image_url, :size => "32x32" , :class => "listing-img" %>
    <% end %>
  </div>

  <div class="span4">
    <div class="pull-right">
      <%= link_to "New Mail" ,"", :class => "btn" %>
    </div>
    <h3>Beta Plan Users</h3><hr/>
    <% for fan in Fan.all[39..71]  do %>
      <%= image_tag fan.image_url, :size => "32x32" , :class => "listing-img" %>
    <% end %>
  </div>

  <div class="span4">
    <div class="pull-right">
      <%= link_to "New Mail" ,"", :class => "btn" %>
    </div>
    <h3>News Letter Subscribers</h3><hr/>
    <% for fan in Fan.all[31..40]  do %>
      <%= image_tag fan.image_url, :size => "32x32" , :class => "listing-img" %>
    <% end %>
  </div>

</div>




<style>

  .listing-img{
    float:left;
    padding:0.6em;
  }
</style>

app/views/email_listings/_running_campaigns.erb
<table class="table">
  <thead>
    <tr>
      <th>Campaign Name</th>
      <th>Sent At</th>
      <th>Recepients</th>
      <th>Opened</th>
      <th>Engadged</th>
      <th>Unsubscribed</th>
    </tr>
  </thead>
  <tbody>
    <% 10.times do  %>
    <tr>
      <td> <%= lorem(4) %> </td>
      <td width="100px"> <%= Time.now.strftime("%m/%d/%y") %></td>
      <td width="80px">  <span class="badge badge-info"> <%= rand(30) %> </span> </td>
      <td width="80px">  <span class="badge badge-success"> <%= rand(30) %> </span> </td>
      <td width="80px">  <span class="badge badge-success"> <%= rand(30) %> </span> </td>
      <td width="80px">  <span class="badge badge-important"> <%= rand(30) %> </span> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/email_listings/_sidebar.erb
<% content_for :sidebar do %>
  <%= render :partial => 'template_carosel' %>
<% end  %>

app/views/email_listings/_template_carosel.erb
<h3>Site Templates </h3><hr/>
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item">
      <img src="http://i3.campaignmonitor.com/templates/neue/45royale/preview/modern_left.jpg" alt="">
      <div class="carousel-caption">
        <h4>First Thumbnail label</h4>
        <%= link_to "Use Me" %>
      </div>
    </div>
    <div class="item">
      <img src="http://i3.campaignmonitor.com/templates/neue/45royale/preview/boutique_right.jpg" alt="">
      <div class="carousel-caption">
        <h4>Second Thumbnail label</h4>
        <%= link_to "Use Me" %>
      </div>
    </div>
    <div class="item active">
      <img src="http://i3.campaignmonitor.com/templates/neue/meagan_fisher/preview/airmail_1.jpg" alt="">
      <div class="carousel-caption">
        <h4>Third Thumbnail label</h4>
        <%= link_to "Use Me" %>
      </div>
    </div>
    <div class="item ">
      <img src="http://i3.campaignmonitor.com/templates/neue/newism/preview/classic_1.jpg" alt="">
      <div class="carousel-caption">
        <h4>Third Thumbnail label</h4>
        <%= link_to "Use Me" %>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

app/views/email_listings/edit.html.erb
<%= render :partial => 'form' %>

app/views/email_listings/index.html.erb
<h1>Email Listings</h1>
<%= lorem(50) %>
<br/>
<br/>
<br/>
<div class="tabbable ">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#1" data-toggle="tab">Running Campaigns</a></li>
    <li><a href="#comments" data-toggle="tab">Drafts</a></li>
    <li><a href="#fans" data-toggle="tab">News Letters</a></li>
    <li><a href="#32" data-toggle="tab">Auto Responders</a></li>
    <li><a href="#33" data-toggle="tab">Templates</a></li>
    <li><a href="#34" data-toggle="tab">Listings</a></li>
  </ul>
  <div class="tab-content">

    <div class="tab-pane active" id="1">
     <%= render :partial => 'running_campaigns' %>
    </div>


    <div class="tab-pane" id="comments">
       <%= render :partial => 'list' %>
    </div>
    <div class="tab-pane" id="fans">
      <h3>Draft Messages</h3><hr/>
      <%= render :partial => 'list' %>
    </div>
    <div class="tab-pane" id="32">
      <h3>Auto Responding Messages</h3><hr/>
      <%= render :partial => 'auto_responders' %>
    </div>
    <div class="tab-pane" id="33">
      <h3>Email Templates</h3><hr/>
      <%= render :partial => 'list' %>
    </div>
    <div class="tab-pane" id="34">
      <h3>My Email Lists</h3><hr/>
      <%= render :partial => 'listings' %>
    </div>
  </div>
</div>




<%= link_to 'New', new_email_listing_path, :class => 'btn btn-primary' %>

<%= render :partial => 'sidebar'  %>

app/views/email_listings/new.html.erb
<%= render :partial => 'form' %>

app/views/email_listings/show.html.erb
<h1>Email Listing</h1>

<p>
  <b>Brand</b><br>
  <%= @email_listing.brand_id %>
</p>

<p>
  <b>Name</b><br>
  <%= @email_listing.name %>
</p>

<p>
  <b>Draft</b><br>
  <%= @email_listing.draft %>
</p>

<p>
  <b>Template</b><br>
  <%= @email_listing.template_id %>
</p>

<p>
  <b>Header</b><br>
  <%= @email_listing.header %>
</p>

<p>
  <b>Body</b><br>
  <%= @email_listing.body %>
</p>

<p>
  <b>Sent at</b><br>
  <%= @email_listing.sent_at %>
</p>

<p>
  <b>Image</b><br>
  <%= @email_listing.image %>
</p>

<p>
  <b>Movie</b><br>
  <%= @email_listing.movie %>
</p>

<p>
  <b>Footer</b><br>
  <%= @email_listing.footer %>
</p>

<p>
  <b>Daily</b><br>
  <%= @email_listing.daily %>
</p>

<p>
  <b>Weekly</b><br>
  <%= @email_listing.weekly %>
</p>

<p>
  <b>Monthly</b><br>
  <%= @email_listing.monthly %>
</p>

<div class="form-actions">
  <%= link_to 'Back', email_listings_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_email_listing_path(@email_listing), :class => 'btn' %>
  <%= link_to 'Delete', email_listing_path(@email_listing), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>