config/routes.rb
Store::Application.routes.draw do
  
  
  
  resources :calls

  get "tropo/callback"
  post "tropo/callback"
  get "tropo/index"

  get "tropo/recordings"

  resources :autoresponders
  
  post "api/parse_google_search"
  get "api/pending_emails"
  post "api/process_emails"
  post "api/process_scan"
  post "api/process_website"
  get "api/process_website"
  get "api/channel_scanned"
  get "api/email_status"
  get "api/export_brand"
  get "api/brands"
  get "api/scan_plan"
  post "api/scan"
  post "api/logs"
  get "api/scan"
  get "api/monitor"

  get 'trackers/load'
  resources :trackers
  resources :scores

  get "emails/delete_all"
  get "emails/send_email"
  resources :emails

  get "feed_entries/show"
  get "feed_entries/deploy"

  resources :tutorials

  post "bulk_mails/add_articles"
  post "bulk_mails/configure"
  get "bulk_mails/move_article"
  get "bulk_mails/stats"
  get "bulk_mails/configure"
  post "bulk_mails/import"
  get "bulk_mails/import"
  get "bulk_mails/duplicate"
  get "bulk_mails/check"
  get "bulk_mails/stop"
  get "bulk_mails/start"
  get "bulk_mails/preview"
  resources :bulk_mails

  resources :forum_posts

  resources :topics

  resources :colors

  resources :mentions

  resources :tickets
  resources :feed_entries

  
  
  get "posts/email_action"
  get "posts/post_to"
  get "posts/repost"
  get "posts/preview"
  get "posts/deploy_to_facebook"
  get "posts/add_to_delayed"
  get "posts/retweet"
  get "posts/follow_user"
  
  get "brands/templates"
  get "brands/search"
  get "brands/searches"
  get "brands/recommendations"
  get "brands/connections"
  get "brands/disconnect"
  get "brands/map"
  get "brands/reading"
  get "brands/exposure"
  get "brands/twitter_search"
  get "brands/twitter_mentions"
  get "brands/repost_rss_items"
  
  
  
  
  get "admin/find_people"
  get "admin/page_preview"
  get "admin/website_templates"
  get "admin/email_templates"
  get "admin/licenses"
  get "admin/licenses"
  get "admin/test"
  get "admin/bgc"

  get "admin/background_jobs"

  get "admin/timeline_json"
  get "admin/reader"
  get "admin/index"
  get "admin/users"
  get "admin/refresh_rss"
  get "admin/delete_all_jobs"
  get "admin/delete_job"
  get "admin/posts"
  get "admin/comments"
  get "admin/websites"

  
  get "slides/create"

  get "slides/edit"

  get "slides/destroy"

  get "slides/index"

  get "slides/update"

  get "slides/new"

  get "channels/create_short_link"
  get "channels/remove_feed"
  get "channels/add_feed"
  get "channels/register"
  post "channels/register"
  get "channels/ignore"
  get "channels/scan"
  get "channels/index"
  get "channels/show"
  post "channels/update"

  get "/users/reset_user"
  get "/users/delete_user"
  
  resources :slides
  resources :channels
  resources :posts

  resources :deployments

  resources :messages

  resources :groups

  get "analysis/index"
  get "analysis/callback"
  get "analysis/fans"
  get "analysis/social_networks"
  get "analysis/mentions"
  get "analysis/website"
  post "analysis/website"
  get "analysis/mailing_list"

  get "inquieries/reply"
  resources :inquieries

  resources :feeds

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions  

  
  
  post "public/form_post"
  get "public/campaign"
  get "public/newsletter"
  get "public/event"
  get "public/email_verification"
  get "public/unsubscribe_from_email"
  get "public/elections"
  get "public/index_heb"
  get "public/meetup"
  get "public/event"
  get "public/facebook_page_public"
  get "public/facebook_page_private"
  get "public/index"
  get "public/tour"
  get "public/blog"
  get "public/prices"
  get "public/beta"
  get "public/store"
  get "public/product"
  get "public/article"
  get "public/register"
  get "public/login"
  get "public/brands"
  get "public/brand"

  get "brands/timeline"
  get "brands/stream"
  get "brands/scan_brand"
  get "brands/social_dashboard"
  get "brands/social_login_callback"
  get "brands/social_login_failure"
  
  match "/auth/:provider/callback", to: "brands#social_login_callback"
  match "/auth/failure", to: "brands#social_login_failure"

  get "page_partials/row_settings"
  get "page_partials/images"
  get "/page_partials/replace_with"
  post "/page_partials/quick_update"
  resources :page_partials

  get "pages/copy_template"
  get "pages/preview_inner"
  get "pages/make_template"
  get "pages/save_colors"
  get "pages/create_page"
  get "pages/add_line"
  get "pages/set_css_template"
  get "pages/export"
  get "pages/add_line"
  get "pages/hero_row"
  get "pages/move_row_top"
  get "pages/move_row_bottom"
  get "pages/move_row_up"
  get "pages/move_row_down"
  get "pages/remove_row"
  get "pages/preview"
  get "pages/css"
  get "pages/layout"
  get "pages/js"
  resources :pages
  
  get "websites/move_page"
  get "websites/create_page"
  get "websites/reset_custom_colors"
  get "websites/apply_color_patch"
  get "websites/css"
  get "websites/stats"
  resources :websites

  get "research/index"
  get "research/rss"
  get "research/people"
  get "research/news"
  get "research/competitors"
  get "research/groups"
  get "research/twitter"

  get "research/groups"
  get "articles/new_article"
  get "articles/publish"
  get "articles/deploy_to_twitter"
  get "articles/deploy_to_facebook_page"
  get "articles/deploy_to_blog_via_email"

  resources :bookmarks

  get "/templates/duplicate"
  get "/templates/preview"
  resources :templates

  resources :email_listings
  get "competitors/scan"
  match '/competitors/:id/scan' => "competitors#scan"
  
  
  get "events/publish"
  get "events/deploy"
  
  post "fans/import"
  get "fans/import"
  get "fans/invite"
  get "fans/ignore" 
  get "fans/search" 
  get "fans/scan" 
  get "fans/follow" 
  get "fans/unfollow" 
  get "fans/competitor" 
  get "fans/charts" 
  
  
  get "products/charts" 
  get "events/charts" 
  
  
  match '/events/:id/publish' => "events#publish"
  match '/events/:id/deploy' => "events#deploy"
  resources :events
  resources :competitors
  resources :comments
  resources :fans
  resources :users
  resources :articles
  resources :brands
  resources :products
  
  get "channels/scan"
  
  match '/channels/:id/scan' => "channels#scan"
  match 'blog/:id' => "public#blog"
  match 'store/:id' => "public#store"
  match 'site/:id' => "public#brand"
  

  root :to => 'public#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  include BrandsHelper
  include TwitterHelper
  include GooglePlusHelper
  include ERB::Util 
  include ScoresHelper
  require 'linkedin'
  
  
  
  # GET /brands
  # GET /brands.json
  def index
    redirect_to  "/brands/#{current_user.brand.id}" #unless current_user.admin?
    #    @brands = Brand.all
  end

  def recommendations
    #    raise params.inspect
  end

  def search
    q = params[:search]
    @prospects =  current_user.brand.find_people(q)
  end
  
  
  def templates
    @emails = Template.where(:kind => "email")
    @newsletters = Template.where(:kind => "email")
    @websites = Template.where(:kind => "website")
  end
  
 
  def connections
    @brand = current_user.brand
    @fb = @brand.get_channel("facebook")
    @tw = @brand.get_channel("twitter")
    @yt = @brand.get_channel("youtube")
    @gm = @brand.get_channel("gmail")
    @rss = @brand.get_channel("rss")
    @gp = @brand.get_channel("google")
    @fs = @brand.get_channel("foursquare")
    @li = @brand.get_channel("linkedin")
    @wp = @brand.get_channel("wordpress")
    @bl = @brand.get_channel("blogger")
  end
  

 
  def searches
    @brand = current_user.brand
  end
  
  def disconnect
    @brand = current_user.brand
    @channel = Channel.find(params[:channel])
    @channel.disconnect
    redirect_to "/brands/connections"
  end
  
  # GET /brands/1
  # GET /brands/1.json
  
  #  require 'twitter'
  def show
    @brand = current_user.brand
    
    for channel in @brand.channels do
      @fb = channel if channel.facebook?
      @tw = channel if channel.twitter?
      @yt = channel if channel.youtube?
      @gm = channel if channel.gmail?
      @rss = channel if channel.rss?
      @rs = channel if channel.rss?
      @gp = channel if channel.google_plus?
      @fs = channel if channel.foursquare?
      @li = channel if channel.linkedin?
      @wp = channel if channel.wordpress?
      @bl = channel if channel.blogger?
    end
    @inquiries = @brand.inquieries
    @comments = @brand.comments.where("channel_id is NOT NULL") 
    @mentions = @brand.comments.where( "kind = 'mention' and channel_id is NOT NULL")
    @competitors_posts = @brand.posts.where(:kind => "competitor-post").order("posted_at DESC").limit(50)
    @jobs = @brand.posts.where(:kind => "job").order("rank desc")
    @messages = @brand.posts.where(:kind => "inbox").order("posted_at DESC").limit(10)
    @content  = []
    @rss.posts.where(:kind => "recommended").each{|p| @content << {:id => p.id, :title => p.title, :body => p.short_body, :image_url => p.img , :target_link => p.target_link} } 
    @li.posts.where(:kind => "job").each{|p| @content << {:id => p.id, :title => p.title, :body => p.short_body, :image_url => p.img , :target_link => p.target_link} } 
   
  


  end
  
  
  def map
    @brand = current_user.brand
    @people = @brand.fans.where("location is not null")
  end
  
  
  
  def exposure
    @brand = current_user.brand
    @fb = @brand.get_channel("facebook")
    @tw_channel = @brand.get_channel("twitter")
    @google_results = google_search( @brand.name)
    @site_url_results = google_search( "http://goo.gl/g8sAs")
    @posted_articles = @brand.posts.where(:kind => "repost")
  end
  
  
  # GET /brands/new
  # GET /brands/new.json
  def new
    redirect_to "/brands"  unless current_user.admin?
    @brand = Brand.new(:user_id => params[:user_id])
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])
    @brand.create_defult_website  
    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    #    raise params.inspect
    @brand = Brand.find(params[:id])
    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        @brand.save
         

        unless params[:brand][:twitter_search] or params[:brand][:twitter_ignore]
          #          @brand.delay.update_channels
          #          @brand.delay.scan
        end

        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
#      ProspectsSearchWorker.perform_async(@brand)  
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
  
  
  def social_login_callback
    note = ""
    #    raise params.inspect
    @brand = current_user.brand
    
    if params[:provider].include? "twitter"
      token = request.env["omniauth.auth"][:credentials][:token]
      secret = request.env["omniauth.auth"][:credentials][:secret]
      
      #      raise "TOKEN:#{token} |    SECERT:#{secret}"
      username = request.env["omniauth.auth"][:info][:nickname]
      @brand.twitter_token = token
      @brand.twitter_secret = secret
      @brand.twitter_user_id = username
      @brand.save
      
      ch = @brand.get_channel("twitter")
      ch.token = token
      ch.secret = secret
      ch.uid = username
      ch.save
      note =  "You are now connected to Twitter!"
      
    end

    if params[:provider].include? "facebook"
      token = request.env["omniauth.auth"][:credentials][:token]
      @brand.facebook_token = token
      @brand.save
      
      ch = @brand.get_channel("facebook")
      ch.token = token
      #      ch.secret = secret
      ch.save
      note =  "You are now connected to Facebook!"
    end

    
    
    if params[:provider].include? "foursquare"
      token = request.env["omniauth.auth"][:credentials][:token]
      secret = request.env["omniauth.auth"][:credentials][:secret]
      ch = @brand.get_channel("foursquare")
      ch.token = token
      ch.save
      note =  "You are now connected to Foursquare!"
    end
    
    if params[:provider].include? "google"
      #      raise request.env["omniauth.auth"].inspect
      token = request.env["omniauth.auth"][:credentials][:token]
      secret = request.env["omniauth.auth"][:credentials][:secret]
      @brand.google_token = token
      @brand.google_secret = secret
      @brand.save
      note =  "You are now connected to Google!"
    end
    
    
    if params[:provider].include? "drop"
#      raise request.env["omniauth.auth"].inspect
      token = request.env["omniauth.auth"][:credentials][:token]
      secret = request.env["omniauth.auth"][:credentials][:secret]
      ch = @brand.get_channel("dropbox")
      ch.token = token
      ch.secret = secret
      ch.save
      note =  "You are now connected to DropBox"
    end

    if params[:provider].include? "linkedin"
      token = request.env["omniauth.auth"][:credentials][:token]
      secret = request.env["omniauth.auth"][:credentials][:secret]
      
      @brand.linkedin_token = token
      @brand.linkedin_secret = secret
      @brand.linkedin_pin= params[:oauth_verifier]
      @brand.save
      
      
      ch = @brand.get_channel("linkedin")
      ch.token = token
      ch.secret = secret
      ch.pin =params[:oauth_verifier]
      ch.save

      note =  "You are now connected to Linkedin!"
    end
    redirect_to "/brands", :notice => note
  end
  
  def social_login_failure
    raise params.inspect
  end
  
  def social_dashboard
    @brand = current_user.brand
    @tw_results =   []
    @tw_mentions = []  #Twitter.search(@brand.name,  :rpp => 100)
    @tw_timeline =  [] #Twitter.user_timeline("assaf604")
    #    raise @tw_timeline.inspect
  end
   
  
  def twitter_search
    @brand = current_user.brand
    @tw_channel = @brand.get_channel("twitter")
    render :layout => "embedded"
  end
  
  
  def scan_brand
    system "sudo thor scan brand #{params[:id]} http://23.21.17.104 #{Rails.root}/../scanner &"
    redirect_to "/brands"
  end


  def repost_rss_items
    ar = []
    params.keys.each{|key| ar << key[6..100] if key.include? "check"}
    Article.create_from_rss_items(ar, current_user.brand.id)
    redirect_to "/articles"
  end
  
  
end

app/helpers/brands_helper.rb
module BrandsHelper

  
  
  
  
end

app/views/brands/_form.html.erb
<%= form_for @brand, :html => { :class => 'form-vertical' } do |f| %>
  <fieldset>
    

    <div class="row-fluid thumbnail">

      <div class="modal-header">
        <div class="pull-right item_command">
          <a href="/brands/<%=@brand.id%>/edit"><i class="icon-info-sign"></i> Brand info</a>
          <a href="/brands/connections"><i class="icon-signal"></i> Connections</a>
          <a href="/brands/searches"><i class="icon-search"></i> Searches </a>
        </div>
        
        <h3>Your business name and slogan</h3>
      </div>

      <div class="modal-body">

        <div class="pull-right">
          <div class="control-group">
            <%= f.label "Brand logo", :class => 'control-label' %>
            <div class="controls">
              <%= f.file_field :image, :class => 'text_field' %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :remote_image_url, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :remote_image_url, :class => 'text_field' %>
            </div>
          </div>

          <%= image_tag @brand.image_url.to_s , :size => "100x100" unless @brand.image_url.nil? %>
        </div>

        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :name, :class => 'text_field' %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "slogan", :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :description, :class => 'text_field span8' %>
          </div>
        </div>


        <div class="control-group">
          <%= f.label "Enter Keywords describing your business", :class => 'control-label '  %>
          <div class="controls">
            <%= f.text_field :keywords, :class => 'text_field span8' %>
          </div>
        </div>
      </div>
      
      <div class="modal-header">
        <h3>Your business address And phones</h3>
      </div>

      <div class="modal-body">
        <table width="100%">
          <tr>
            <td width="30%">
              <div class="control-group">
                <%= f.label :phone, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :phone, :class => 'text_field' %>
                </div>
              </div>


              <div class="control-group">
                <%= f.label :fax, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :fax, :class => 'text_field' %>
                </div>
              </div>

            </td>
            <td>
              <div class="control-group">
                <%= f.label :address, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_area :address, :class => 'text_area' %>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>
      
      
       <div class="modal-header">
        <h3>Links to Social Networks and blogs</h3>
      </div>

      <div class="modal-body">
        <p> The social machine will add these links to your emails and website</p>
        <table width="100%">
          <tr>
            <td>
              <div class="control-group">
                <%= f.label :facebook_page, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :facebook_page, :class => 'text_field' %>
                </div>
              </div>
            </td>
            <td>
              <div class="control-group">
                <%= f.label :twitter_user_id, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :twitter_user_id, :class => 'text_field' %>
                </div>
              </div>
            </td>
            <td>
              <div class="control-group">
                <%= f.label :youtube_url, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :youtube_url, :class => 'text_field' %>
                </div>
              </div>
            </td>
            <td>
              <div class="control-group">
                <%= f.label :linkedin_url, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :linkedin_url, :class => 'text_field' %>
                </div>
              </div>
            </td>
          </tr>
        </table>
        
        
      </div>
      
      
      <div class="modal-header">
        <h3>Incomming Email</h3>
      </div>

      <div class="modal-body">
        <table width="100%">
          <tr>
            <td width="100%">
              <div class="control-group">
                <%= f.label :gmail_email, :class => 'control-label' %>
                <div class="controls">
                  <%= f.text_field :gmail_email, :class => 'text_field' %>
                </div>
              </div>
              <div class="control-group">
                <%= f.label :gmail_pwd, :class => 'control-label' %>
                <div class="controls">
                  <%= f.password_field :gmail_pwd, :class => 'secret' %>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>
      
      <div class="modal-footer">
        <div class="pull-right item_command">
       <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to 'Cancel', brands_path, :class => 'btn' %>
      &nbsp;
      &nbsp;
    </div>
      </div>
    </div>
    <br/>

   
    </fieldset>
  <% end %>

<style>
  .modal-footer{margin-bottom: -5px;margin-left: -4px;;margin-right: -4px;}
</style>

app/views/brands/_form_searches_tab.erb
<h3>Realtime Twitter Searches</h3><hr/>

<div class="control-group">
  <%= f.label :twitter_search, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :twitter_search, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :twitter_ignore, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :twitter_ignore, :class => 'text_field' %>
  </div>
</div>

<h3>RSS Feed Searches</h3><hr/>

<div class="control-group">
  <%= f.label :rss_search, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :rss_search, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :rss_ignore, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :rss_ignore, :class => 'text_field' %>
  </div>
</div>

app/views/brands/_form_shared_drive_tab.erb
<h3>Shared Drives</h3>
<table class="table">
  <tr>
    <td width="65px">
      <%= image_tag "/assets/icons/dropbox_64.png" %>
    </td><td>
      <div class="control-group">
        <%= f.label "Dropbox Token", :class => 'control-label' %>
        <div class="controls">
          <%#= f.text_field :facebook_token, :class => 'text_field' %>
        </div>
      </div>
    </td><td>
      <div class="control-group">
        <%= f.label "Dropbox images path", :class => 'control-label' %>
        <div class="controls">
          <%#= f.text_field :facebook_page, :class => 'text_field' %>
        </div>
      </div>
    </td><td>
      <br/>
      <%= link_to "Login with Dropbox" , "/auth/facebook" , :class => "btn"  %>
    </td>
  </tr>
  <tr>

    <td>
      <%= image_tag "/assets/icons/google_drive_64.png" %>
    </td><td>
      <div class="control-group">
        <%= f.label "Google Drive Token", :class => 'control-label' %>
        <div class="controls">
          <%#= f.text_field :twitter_user_id, :class => 'text_field' %>
        </div>
      </div>
      </td><td>
      <%= link_to "Login with Google Drive" , "/auth/twitter" , :class => "btn"  %>
    </td>
    </td>
  </tr>
  <Tr>
  <td>
      <%= image_tag "/assets/icons/skydrive_64.png" %>
    </td><td>
      <div class="control-group">
        <%= f.label "Microsoft SkyDrive Token", :class => 'control-label' %>
        <div class="controls">
          <%#= f.text_field :google_page, :class => 'text_field' %>
        </div>
      </div>
      </td><td>
    </td>
  </tr>
  <Tr>
  <td>
      <%= image_tag "/assets/icons/amazon_s3_64.png" %>
    </td><td>
      <div class="control-group">
        <%= f.label "Amazon S3 Token", :class => 'control-label' %>
        <div class="controls">
          <%#= f.text_field :forsquare_venue, :class => 'text_field' %>
        </div>
      </div>
          </td><td>
      </td><td>
      <%= link_to "Login with Amazon S3" , "/auth/foursquare" , :class => "btn"  %>
    </td>
  </tr>
</table>

app/views/brands/_form_social_tab.erb
<h3>Social Networks</h3>
<table class="table">
  <tr>
    <td width="65px">
      <%= link_to image_tag("/assets/icons/facebook_64.png", :size => "32x32")  + " Login" , "/auth/facebook" , :class => "btn"  %>
    </td><td>
      <div class="control-group">
        <%= f.label :facebook_token, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :facebook_token, :class => 'text_field' %>
        </div>
      </div>
    </td><td>
      <div class="control-group">
        <%= f.label :facebook_page, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :facebook_page, :class => 'text_field' %>
        </div>
      </div>
    </td>
  </tr>
  <tr>

    <td>
      <%= link_to image_tag("/assets/icons/twitter_64.png", :size => "32x32") + " Login"  , "/auth/twitter" , :class => "btn"  %>
    </td><td>
      <div class="control-group">
        <%= f.label :twitter_user_id, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :twitter_user_id, :class => 'text_field' %>
        </div>
      </div>
      </td><td>
        <div class="control-group">
        <%= f.label :twitter_token, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :twitter_token, :class => 'text_field' %> <%#= @brand.twitter_secret %>
        </div>
      </div>
    </td>
    </td>
  </tr>
  
  <Tr>
  <td>
    <%= link_to image_tag("/assets/icons/linkedin_64.png", :size => "32x32")   + " Login"  , "/auth/linkedin" , :class => "btn"  %>
    </td><td>
      <div class="control-group">
        <%= f.label :linkedin_token, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :linkedin_token, :class => 'text_field' %>
        </div>
      </div>
          </td><td>
      <div class="control-group">
        <%= f.label :linkedin_secret, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :linkedin_secret, :class => 'text_field' %>
        </div>
      </div>
          </td><td>
      <div class="control-group">
        <%= f.label :linkedin_pin, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :linkedin_pin, :class => 'text_field' %>
        </div>
      </div>
    </td>
  </tr>
  
   <Tr>
  <td>
    <%= link_to image_tag("/assets/icons/google_64.png", :size => "32x32")  + " Login"  , "/auth/google_oauth2" , :class => "btn"  %>
    </td><td>
      <div class="control-group">
        <%= f.label :google_token, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :google_token, :class => 'text_field' %>
        </div>
      </div>
          </td><td>
      <div class="control-group">
        <%= f.label :google_secret, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :google_secret, :class => 'text_field' %>
        </div>
      </div>
    </td>
          </td><td>
      <div class="control-group">
        <%= f.label :google_page, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :google_page, :class => 'text_field' %>
        </div>
      </div>
    </td>
  </tr>
  
  
  <Tr>
  <td>
    <%= link_to image_tag("/assets/icons/foursquare_64.png", :size => "32x32")  + " Login"  , "/auth/foursquare" , :class => "btn"  %>
    </td><td>
      <div class="control-group">
        <%= f.label :forsquare_venue, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :forsquare_venue, :class => 'text_field' %>
        </div>
      </div>
          </td><td>
      <div class="control-group">
        <%= f.label :foursquare_token, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :foursquare_token, :class => 'text_field' %>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/brands/edit.html.erb
<%= render :partial => 'form' %>

<% content_for :sidebar do  %>
    <%= render :partial => 'edit_sidebar' %>
<% end %>

app/views/brands/new.html.erb
<%= render :partial => 'form' %>
<%= render :partial => "new_sidebar" %>